# Github workflow to compile latex and deploy the pdf to an orphan branch.
# The latest compiled pdf is made available at e.g.
# https://github.com/dgerosa/reponame/blob/build/filename.pdf
# Davide Gerosa (2021) https://github.com/dgerosa

name: writeapaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      # Modifica la directory dove si trova il file .tex
      DIR: L06/L06-Q3/paper
      FILE: aanda
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LaTeX compile
        uses: xu-cheng/texlive-action@v2
        with:
          run: |
            # Cambia nella cartella in cui si trova il file .tex
            cd ${{ env.DIR }}
            # Compila il file .tex e crea il PDF
            pdflatex ${{ env.FILE }}
            bibtex ${{ env.FILE }}
            pdflatex ${{ env.FILE }}
            pdflatex ${{ env.FILE }}

      - name: Move PDF to artifacts folder
        run: |
            # Crea la cartella github_artifacts se non esiste
            mkdir -p github_artifacts
            # Sposta il file PDF generato nella cartella temporanea
            mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: ./github_artifacts/${{ env.FILE }}.pdf

  deploy:
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.FILE }}.pdf
          path: github_artifacts

      - name: Move PDF to deployment folder
        run: |
            mkdir -p github_deploy
            mv github_artifacts/*/* github_deploy

      - name: Create the build branch if it doesn't exist
        run: |
            git checkout --orphan build
            git push origin build

      - name: Deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true

  clean:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Delete PDF artifact
        uses: geekyeggo/delete-artifact@v4
        with:
          name: '*.pdf'

